spring:
  liquibase:
    change-log: classpath:liquibase/changelog.xml
  #h2:
  #  console:
  #    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  data:
    rest:
      base-path: /datarest
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#      base-path: /monitor
#  endpoint:
#    health:
#      show-details: always
logging:
  level:
    root: warn
  pattern:
    console: "%msg%n"
  #file:
  #  path: ./otus-jdbc/logs/
  #  name: ${logging.file.path}/libcat.log
mail:
  email: otustask@mail.ru
  password: ckj;ysqgfhjkm1234