spring:
  data:
    mongodb:
      url: mongodb://localhost
      port: 666
      database: libcat
  liquibase:
    change-log: classpath:liquibase/changelog.xml

logging:
  level:
    root: warn
  pattern:
    console: "%msg%n"