spring:
  application:
    name: Tasker
  liquibase:
    change-log: classpath:liquibase/changelog.xml
  h2:
    console:
      enabled: true
  data:
    rest:
      base-path: /datarest
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitor
  endpoint:
    health:
      show-details: always
logging:
  level:
    root: warn
  pattern:
    console: "%msg%n"
  file:
    path: ./otus-jdbc/logs/
    name: ${logging.file.path}/libcat.log
mail:
  email: otustask@mail.ru
  password: ckj;ysqgfhjkm1234
