DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID BIGSERIAL PRIMARY KEY, FULLNAME VARCHAR(255));
DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID BIGSERIAL PRIMARY KEY, TITLE VARCHAR(255));
DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID BIGSERIAL PRIMARY KEY, TITLE VARCHAR(255),AUTHOR BIGINT,GENRE BIGINT,
foreign key (AUTHOR) references AUTHORS(ID),
foreign key (GENRE) references GENRES(ID));


