CREATE TABLE AUTHORS(
    ID BIGSERIAL PRIMARY KEY,
    FULL_NAME VARCHAR(255));

CREATE TABLE GENRES(
    ID BIGSERIAL PRIMARY KEY,
     TITLE VARCHAR(255));

CREATE TABLE COMMENTS(
    ID BIGSERIAL PRIMARY KEY,
    TEXT VARCHAR(255),
    book_id BIGINT);

CREATE TABLE BOOKS(
    ID BIGSERIAL PRIMARY KEY,
    TITLE VARCHAR(255),
    AUTHOR_ID BIGINT references AUTHORS(id),
    GENRE_ID BIGINT references GENRES(id),
    COMMENT_ID BIGINT references COMMENTS(id) on delete cascade);



